### ISSUE TITLE
word press vulnerable

### ISSUE THREAD

**Issue by rparson1** [Rundiz-WP/okv-oauth#2]
WP 5.0.3
After customizing a theme I made it public. It is now on the internet. The problem is that
on each page where the title is or not there is a EDIT text and if you click on it
it takes you to the site admin page, which means anyone can do whatever.
Thank you
Richard

**Comment by ve3** [comment]
Hello,

Which files do you modify as your theme?
Could you please capture the screenshot for that page (where there is a "edit" text)? Please censored important parts on your screenshots before upload.
And please show me the URL path (example: /wordpress-installed-path/wp-admin/what-page-to-go.php) that the edit link go to. I'm not sure what editing page it is.

On front-end, this plugin use the template files from this location if it is not in your theme ( https://github.com/Rundiz-WP/okv-oauth/tree/master/templates ) and I don't see anywhere to go to edit anything except change the email.
However if you provide me more info I asked I can inspect more that what is wrong with it.

Thank you.

**Comment by rparson1** [comment]
Thank you for answering.

    Since I posted it is no longer doing that. Don't have an answer but I
am happy to see that it is working OK.
Thanks for trying.
Richard

**Comment by ve3** [comment]
OK. Please reply this issue whenever it happens again.
